version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase1
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123
    ports:
      - "3305:3306"